# -*- coding: utf-8 -*-
"""Aktuelle Luftmesswerte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sIYZJkAhHrgnm0DjKeBDg4rzyi3cJUx
"""

import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

url = ("https://lupo-cloud.de/air-app/table?component=luft-lqi&id=DEBW118") # neue Adresse von der website abrgreifen

df = pd.read_json(url)

df

# Extract column names from the 'header' row of the 'table' column
headers_list = df.loc['header', 'table']
column_names = [item['label'] for item in headers_list]

# Extract the actual data from the 'data' row of the 'table' column
data_list_of_dicts = df.loc['data', 'table']
actual_data = [item['data'] for item in data_list_of_dicts]

clean_df = pd.DataFrame(actual_data)
print(clean_df.shape)  # see the true dimensions

# If there are indeed 12 columns, some headers may be missing
# Assign what you have and label the rest
if clean_df.shape[1] > len(column_names):
    column_names += [f"extra_{i}" for i in range(clean_df.shape[1] - len(column_names))]

clean_df.columns = column_names
clean_df.to_csv('lufttabelle.csv')

clean_df

abruf = requests.get (url)

suppe = BeautifulSoup (abruf.text, "lxml")